### ISSUE TITLE
Enhancement: Additional features required

### ISSUE THREAD

**Issue by kashalls** [OneUptime/helm-chart#1]
Thanks for working on getting this helm chart published. It makes it easier to manage this instead of a huge glob of manifests. We do have some issues that needs to be sorted out.

1. Some of the additional charts included in this chart need a way to be disabled.

Clickhouse, Minio, Postgres and Redis are already scaled services I run. Postgres and Redis are widely available as managed services by hosting companies so it would make sense to that over a small one in this chart. This would need to basically have an option where you can set enabled as a boolean and configure some other things on where to connect, how to connect, connect with special options (redis with sentinel?).

2. I'm not entirely sure why we need metallb in a helmchart?

3. There is no way to pass secret data. Environment variables like [the ones in example.env](https://github.com/OneUptime/oneuptime/blob/8ab7fbc95d295ae4c14e5e27866ac5ff4c0c9293/config.example.env), are unsettable here.

It's true that they are added [here](https://github.com/OneUptime/helm-chart/blob/master/oneuptime/templates/secrets.yaml). But it simply generates a random string, unless these need to be changing every time you deploy this chart.

A good alternative would be to allow users to create a Secret/ConfigMap called `oneuptime-config` for the helmchart to read from instead of hardcoding stuff in helpers.tpl

4. It might be a good idea to explore alternatives to running a nginx container in kubernetes when you can take advantage of other options like traefik, ingress-nginx, or the built-in endpoints that I haven't taken a look into.

All in all, good job on the chart! Glad it is being pushed, a lot of the OSS homelabbers will be happy to stop updating 25 oneuptime containers every day. :)

**Comment by InputObject2** [comment]
This is a read-only repo according to the readme. Issues should be opened on the main (oneuptime/oneuptime) repo.

**Comment by nawazdhandala** [comment]
Closing this issue here.
