### ISSUE TITLE
Fresh install fails. Postgresql shows [1097] FATAL:  password authentication failed for user "oneuptime"

### ISSUE THREAD

**Issue by peterbaumert** [OneUptime/helm-chart#5]
Hi,

when I try to install this helm chart, after issuing the install command all the pods come in "creating" sate and after a while a a a lot of errors show.

One thing i notice is that postgresql pod show this in log

```
[1097] FATAL:  password authentication failed for user "oneuptime"
```

nginx says:

```
{
  timestamp: 1710508488296000,
  traceId: undefined,
  spanId: undefined,
  traceFlags: undefined,
  severityText: undefined,
  severityNumber: 17,
  body: 'password authentication failed for user "oneuptime"',
  attributes: {}
}
```

**Comment by xorl** [comment]
Delete the PV/PVC, and delete the postgresql pod. Should start up after that, also validate that the secrets have deployed.
