### ISSUE TITLE
Error: URL http://localhost/api/project/list-user-projects?limit=50&skip=0 is not available.

### ISSUE THREAD

**Issue by DanielCastronovo** [OneUptime/helm-chart#8]
Hello,

On a fresh install we have an error when i try to access to the dashboard.

`Error: URL http://localhost/api/project/list-user-projects?limit=50&skip=0` is not available.

All pods are in ready state.
No error logs.

Helm chart : `oneuptime-7.0.2721`

**Comment by marcoadasilvaa** [comment]
Same error, helmchart version: oneuptime-7.0.2774
